/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvidenceIdRouteImport } from './routes/evidence.$id'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceIdRoute = EvidenceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EvidenceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/evidence': typeof EvidenceRouteWithChildren
  '/workflow': typeof WorkflowRoute
  '/evidence/$id': typeof EvidenceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/evidence': typeof EvidenceRouteWithChildren
  '/workflow': typeof WorkflowRoute
  '/evidence/$id': typeof EvidenceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/evidence': typeof EvidenceRouteWithChildren
  '/workflow': typeof WorkflowRoute
  '/evidence/$id': typeof EvidenceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/capture' | '/evidence' | '/workflow' | '/evidence/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/capture' | '/evidence' | '/workflow' | '/evidence/$id'
  id:
    | '__root__'
    | '/'
    | '/capture'
    | '/evidence'
    | '/workflow'
    | '/evidence/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptureRoute: typeof CaptureRoute
  EvidenceRoute: typeof EvidenceRouteWithChildren
  WorkflowRoute: typeof WorkflowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/$id': {
      id: '/evidence/$id'
      path: '/$id'
      fullPath: '/evidence/$id'
      preLoaderRoute: typeof EvidenceIdRouteImport
      parentRoute: typeof EvidenceRoute
    }
  }
}

interface EvidenceRouteChildren {
  EvidenceIdRoute: typeof EvidenceIdRoute
}

const EvidenceRouteChildren: EvidenceRouteChildren = {
  EvidenceIdRoute: EvidenceIdRoute,
}

const EvidenceRouteWithChildren = EvidenceRoute._addFileChildren(
  EvidenceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptureRoute: CaptureRoute,
  EvidenceRoute: EvidenceRouteWithChildren,
  WorkflowRoute: WorkflowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
